# target: dependencies
# <tab> rule

# make (without arguments) executes first rule in file
# Ideally, one target for every object file and a target for final binary. 

floodfill: recurse.o floodfill.o
	     c99 -o floodfill recurse.o floodfill.o


recurse.o: recurse.c
	    c99 -c recurse.c

floodfill.o: floodfill.c
	c99 -c floodfill.c